print("Program starting.")
print("Estimate how many minutes you spent on programming...")
num1=int(input("A1_T1:"))
num2=int(input("A1_T2:"))
num3=int(input("A1_T3:"))
num4=int(input("A1_T4:"))
num5=int(input("A1_T5:"))
num6=int(input("A1_T6:"))
num7=int(input("A1_T7:"))
print(f"In total you spent {num1 + num2 + num3 + num4 + num5 + num6 + num7} minutes on programming.\nAverage per task was {(num1 + num2 + num3 + num4 + num5 + num6 + num7) / 7} min and same rounded to the nearest integer {round((num1 + num2 + num3 + num4 + num5 + num6 + num7) / 7)} min.\nProgram ending.")