print("Program starting.")
brand = input("Insert car brand: ")
model = input("Insert car model: ")
print(f'Car brand is "{brand}" and the model is', end=" ")
print(f"'{model}'.", sep="")
print("Program ending.")